= Roadmap to Partnership 

== 1. Introduction call 

We look forward to meeting you (virtually) during a 25- minute call. You can easily schedule on link:https://calendly.com/datamine[our Calendly page] or email us at datamine@purdue.edu

Before our meeting, please review the introduction videos and content on the Corporate Partners home page (datamine.purdue.edu/corporate)

== 1. Check-in call 

We look forward to checking in with you during a 25-minute call. You can easily schedule here on link:https://calendly.com/datamine[our Calendly page].



== 2. Project Description 

Define your project and follow our xref:project_descriptions.adoc[project description guidelines].

== 3. Legal & Funding

=== Sponsor Acknowledgement

Our industry partners sign this Sponsor Acknowledgment link:https://datamine.purdue.edu/corporate/docs/sponsoracknowledgment.docx[(click here to download)].


=== NDA
• Most companies require the students and Data Mine staff to sign a NDA at
the start of the project
• The NDA is provided by the company.
• The NDA must be between an individual (student or staff) and the company. Purdue will not sign a NDA on behalf of the students

=== IP
• Students retain their IP and can license or assign it to the company at no
cost.
• [More details here]
• No for faculty and staff under SA agreement. 

=== Funding
There are two funding levels for our credit-bearing student experience: 

* $20,000 for 5 students and 1 project
* $40,000 for 25 students and multiple projects

An invoice will be sent electronically after your sponsor acknowledgment is fully executed.

== 4. Planning & Project Charter

== 5. Student Alignment 

== FAQs

*What is the time commitment?*

During the academic year, from late August until the end of April, mentors meet with their students for 50 minutes per week. This meeting is usually online unless the mentor is local or visiting West Lafayette. 

*What resources do we get for mentoring a team?*

* 1 paid team leader per project 
* Team of undergraduate and graduate students of diverse backgrounds
* Data Scientist support 
* Corporate Partner Manager 
* Connections to campus partners 

