= Roadmap to Partnership & Renewal

== 1. Let's discuss - schedule a call

Whether this is your first introduction to The Data Mine or you've partnered with us for multiple years, we look forward to discussing with you during a 25-minute call. You can easily schedule on link:https://calendly.com/datamine[our Calendly page] or email us at datamine@purdue.edu


== 2. Project Description 

Define your project and follow our xref:project_descriptions.adoc[project description guidelines]

== 3. Legal & Funding

Our industry partners sign this Sponsor Acknowledgment link:https://datamine.purdue.edu/corporate/docs/sponsoracknowledgment.docx[(click here to download)]. Most partners require students and staff to sign a NDA. Students can also sign an IP agreement. Funding levels are listed in the  Sponsor Acknowledgment. 

xref:legal.adoc[Click here] to view more details regarding legal and funding. 


== 4. Planning & Project Charter

We look forward to meeting with you every other week for 25 minutes during the summer to plan the specifics of your project(s). 

== 5. Student Alignment 

Once we have your project description from step #2, students will start selecting projects in late March through August. 

== 6. Academic Year 

All of our projects in Corporate Partners last the entire academic year from late August through early May. 

=== Fall Semester 

Fall 2022 courses begin on Monday, August 22, 2022. 

=== Spring Semester 

Projects continue through the spring semester and culminate at our Corporate Partners Symposium with a poster session. 

== 7. Renewal

We look forward to building a lasting relationship with your company and hope to partner for many years! The renewal process for the next academic year (August - May) starts in January, but we are happy to discuss additional projects any time of the year. 

== Questions? 

Check out our xref:faq.adoc[FAQ page] or email us. 



