
= Final Presentation - Fall 2021 

Your final presentation will be completed as a group during your last regularly scheduled 50-minute team meeting the week of December 6 - December 10, 2021.

A draft of your presentation is due at the end of sprint #6 on Sunday, November 14. 

This final presentation is worth 22% of your grade and will help you prepare for The Data Mine Corporate Partner Symposium in April 2022.

The presentation will be ~35 minutes long with 15-20 minutes for discussion.

== Guidelines 

The Data Mine Corporate Partners Final Presentations will showcase the hard work of students this semester and their goals for spring 2021. It will help everybody get on the same page and make sure all team members have a thorough understanding of the work. Knowing how to *do* something and knowing how to *explain* something are two different skills, and it is important to be skilled at both.
 
**Research for fall 2021 should NOT stop at this draft. Continue working on your research and you may continue to update the slides up until the day of your presentation **

== When
The final presentation will occur during your last 50-minute team meeting of the semester, during the week of Monday, December 6 – Friday, December 10, 2021. 

== Expectations 

•	**Each student must contribute to the presentation in some capacity. **  
•	Not every student needs to speak during the presentation, but if you don’t speak during the presentation, consider answering a question during Q&A. 
•	For example, here are some suggested roles students can fill (not required to be broken up this way):
    - Student 1: introduction
    - Student 2: summary
    - Student 3: formatting 
    - Student 4: script/notes for the presentation
    - Students 5-10: talk and give the presentation
    - Students 11-14: answer questions after the presentation 

== Design

•	The presentation should look professional. A Purdue template was shared with you via Sharepoint. You are welcome to change the formatting to company branded slides. 

== Content 
*Introduction/Background/Motivation (~10%)*

- Include a slide with team profile (picture with name and major of each student)
- Introduce the project and provide a brief background (there will be colleagues at the presentation that will likely not be familiar with your project)

*Fall 2021 work (~45%)* 

- Summarize your work this semester. Do not go too deep into the nitty gritty details (you should not have screenshots or pasted code in your presentation). 
- Feel free to include a demo (outside of a PowerPoint) if this is relevant to your team.

*Spring 2022 goals (~40%)* 

- Include your plan for spring 2022. Be strategic and discuss what you plan to accomplish by when and how you define a “success”. 

*Summary (~5%)* 

- Include a slide of references and acknowledgements. Thank your mentors and any faculty members.
- Summarize your presentation briefly and open the floor to discussion and questions

*Other Tips*

- The percentages in parenthesis are approximations of how much you should spend talking about each section. It is important to be strategically planning for your spring 2022 goals which is why ~40% of the presentation should be prospective. 
- Make sure to make your slides interesting – include pictures/figures/screenshots. 
- Limit text when possible. 
- Be aware of your audience. Ask your Corporate Partner Mentor who will be coming to the presentation. Some may have technical experience whereas others have business domain experience.  
- The presentation does not have to hide company protected material because these presentations will only be given to internal colleagues to the companies. These presentations will *not* be shared publicly like the posters in the spring semester. 
- Plan out who will be speaking for each section, how much time each team member will have to speak, and how to transition between speakers smoothly. 
- Practice! Practice! Practice! This is your final presentation of the semester. Make sure to practice and prepare. 

== Length 

•	The team meeting is 50 minutes. 
•	Your presentation should be 30-40 minutes with 10-15 minutes for questions and discussion. 
    - You should prepare a few questions to get the Q&A started if no guests have questions right away. Practice answering questions that you think may come up. Take turns answering them too. 
•	Make sure to leave time for a demonstration *if* you are including one. This does not apply to all groups. 

== Grading 

The final presentation is worth 22% of your fall 2021 grade (per the syllabus). The final presentation and deliverable grades will be determined in collaboration with The Data Mine staff and Corporate Partner Mentors. 

*Final Group Presentation......................................................................................22%*

Draft (practice presentation, draft deliverables)................4%

Final Deliverables (slides)................................10%	

Final Presentation................................8%	



== Draft 

A draft of your presentation is due *Sunday, November 14*. The reason your draft is due this early is to allow The Data Mine staff and Corporate Partners Mentors to review the material and provide feedback. 

Each TA will submit the draft link on behalf of the team. The presentation should be created and shared in PowerPoint online. 

Your draft should include all slides that you plan to include. 60%+ of slides should be complete, but some may be “placeholders” and have outlines or notes if you are still working on your fall 2021 research.

**Research for fall 2021 should *NOT* stop at this draft. Continue working on your research and you may continue to update the slides up until the day of your presentation **

== Deliverables 
 
- [Draft Version] PowerPoint Presentation 
- [Final Version] One PowerPoint presentation
        - If you have multiple sub-teams, you should still have 1 presentation overall. 
- [Optional, dependent on team] Interactive demonstrations (as appropriate) like R Shiny, Tableau, mobile app
- [All students] Participation at the presentation 


== Due Dates

- DRAFT presentation due by 11:59 PM ET on Sunday, November 14, 2021 (your TA will submit this)
- FINAL version of presentation due by Sunday, December 5, 2021 by 11:59 PM ET


*table missing here*

== Questions? 

•	Ask your TA 
•	Email us anytime at betz@purdue.edu or datamine@purdue.edu 
•	Stop by our offices in MRGN 
