= Spring 2022 Announcements for Corporate Partner Mentors 


*Announcements will be emailed out to mentors and also logged here.*


== (January 7) Updates for Spring 2022

We hope you enjoyed the holiday break and are off to a great year! Spring 2022 semester at Purdue starts on *Monday, January 10* so we have some updates to share. 

*50-minute Team Meetings start MONDAY!*

Team meetings will begin next week starting on Monday, January 10. The schedule of meeting times is listed here: https://the-examples-book.com/crp/spring2022_locations 
Corporate Partner Mentors attend the 50-minute “lec” time listed. You should have received a recurring calendar invite in December with the meeting time and MS Teams link for the 50-minute mentor meetings. If you do not have this invite, please contact us. The majority of meeting times did not change between fall to spring. 

*Symposium*

Save the date for our 2021-2022 Symposium on Tuesday, April 12, 2022. The Data Mine Symposium showcases the research of our students throughout the academic year via a poster session. The Symposium is currently scheduled for in-person, but we are closely monitoring Purdue policy for any changes. 

*Fall 2022 – Spring 2023 Planning*

It’s not too early to start planning ahead for your project(s) next fall. Students register for their fall 2022 courses in March. We are requesting the brief project descriptions be submitted by February 15. We look forward to meeting with you soon to discuss your plans for next academic year. 

*News Updates*

The American Statistical Association in collaboration with The Data Mine was recently awarded a National Science Foundation grant to support Minority Serving Institutions in The National Data Mine Network:  https://www.purdue.edu/newsroom/releases/2021/Q4/purdues-data-mine-is-making-data-science-accessible-for-all.html 

You can follow along with updates on our LinkedIn page: https://www.linkedin.com/company/datamine-purdue/ 

*Course content*


The Examples Book has been the source of our 1 credit seminar content for the past 2 years. Now, Corporate Partners has an appendix in The Examples Book. We have migrated all of our content away from Brightspace (student-facing only) and into The Examples Book (public and accessible to all). We aspire to be more transparent between The Data Mine and our partner companies and universities, as well as making content and resources readily available for our students. You will see that we have a blank section in the book for Corporate Partner Mentors. We are still developing this content, but you are always welcome to contribute too! The Examples Book is a living document and always under construction. 

*Corporate Partners spring 2022 page for students: https://the-examples-book.com/crp/spring2022
*Home page for The Examples Book: http://the-examples-book.com/ 

*Visiting Campus*

Current Purdue policy still allows for guests to visit campus. If you would like to plan a visit to campus, please let us know. We also have a guest suite in Hillenbrand for overnight stays that is free to guests when visiting campus to meet with students. 

*Staff Updates*

Our team is continuing to grow! We have 14 staff members now. In addition to staff members listed here (https://datamine.purdue.edu/about/welcome.html), we recently welcomed Corporate Partners Senior Manager, Shuennhau Chang, and two new limited-term lecturers. 

We also have a current opening for a Corporate Partners Technical Specialist (https://careers.purdue.edu/job/West-Lafayette-Corporate-Partners-Technical-Specialist-IN-47906/812893500/) on our team if you have interested colleagues. 

We look forward to working with you this semester! 


