= Scrum Team Roles

Considering the personnel and their strengths on every sprint team is crucial for team success. Designated individual roles will help teams stay organized and will establish clear, individual responsibilities. The three roles on a scrum team are product owner, scrum master, and development team. 

The *product owner* is connected directly to the product’s business application. This person provides detailed explanation of product applications and tells the development team what is important to deliver. They set clear directions for the team, balance stakeholder expectations, and understand customer needs. 

The *development team* is comprised of the team members that will do the work. These team members take ownership of tasks made by the product owner and establish these tasks as a part of their sprint. Great development teams have a broad background of experiences and use their strengths to swiftly complete tasks. Their main responsibilities include delivering work throughout the sprint and ensuring transparency in their development. 

The final role within a scrum team is the *scrum master*. This role ensures that scrum is running smoothly and effectively. They are the bridge between product owners and the development team by coordinating valuable product updates with product owners and ensuring work gets completed by the development team. Scrum masters ensure transparency between all team members, create defined sprint schedules, teach sprint values, and most importantly, serve the scrum team to allow for smooth development. 

== Scrum Team Roles in The Data Mine

The Data Mine has a natural definition of who takes on what roles within a scrum team. 

Corporate partner mentors take on the role of product owner because of their direct connection to the business. 

Purdue students make up the development team and perform the work necessary to complete the project. 

TAs work as scrum masters and are the bridge between CP mentors and Purdue students. They establish Agile management and teach scrum to the team.  